// const min = Math.min;
// const max = Math.max;
// console.log(min);
// console.log(max);
const min = Math.min(45, 2, 5, 25, 33,);
console.log(min);
const max = Math.max(45, 2, 5, 25, 33,);
console.log(max);
const py = Math.PI.toFixed(2);
console.log(py);
console.log(Math.abs(15 - 1));
console.log(Math.round(2.4));
console.log(Math.round(2.85));
console.log(Math.floor(2.95));
console.log(Math.ceil(2.01));
console.log(Math.random());
console.log(Math.random() * 10);
const rand = Math.round(Math.random() * 10000);
console.log(rand);